/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SessionDto } from './sessionDto';


export interface AvailabilityDto { 
    siteId?: number;
    fieldId?: number;
    date?: string;
    availableSessions?: Array<SessionDto>;
}

