/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Site } from './site';


export interface Field { 
    fieldId?: number;
    isIndoor?: boolean;
    isActive?: boolean;
    maintenanceFromDate?: string;
    maintenanceToDate?: string;
    site?: Site;
}

