/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FinancialRecordDto { 
    paymentDate?: string;
    amount?: number;
    userFullName?: string;
    siteName?: string;
    paymentMethod?: string;
}

