/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SiteInfo } from './siteInfo';


export interface InfoControllerDto { 
    sites?: number;
    fields?: number;
    siteInfoList?: Array<SiteInfo>;
}

