/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MatchDto } from './matchDto';
import { UserProfileDto } from './userProfileDto';
import { MatchPaymentDto } from './matchPaymentDto';
import { SiteDto } from './siteDto';
import { FieldDto } from './fieldDto';


export interface InvitesDto { 
    payment?: MatchPaymentDto;
    match?: MatchDto;
    field?: FieldDto;
    site?: SiteDto;
    organiser?: UserProfileDto;
    participants?: Array<UserProfileDto>;
    occupancy?: number;
    remainingSlots?: number;
}

