/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MatchDto } from './matchDto';
import { SiteDto } from './siteDto';
import { FieldDto } from './fieldDto';


export interface MatchSiteFieldDto { 
    match?: MatchDto;
    field?: FieldDto;
    site?: SiteDto;
}

