/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Match } from './match';


export interface MatchPayments { 
    tr?: number;
    user?: User;
    match?: Match;
    amount?: number;
    paymentDate?: string;
    status?: string;
    paymentMethod?: string;
}

