/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Match } from './match';


export interface MatchPlayerDto { 
    matchPlayerId?: number;
    match?: Match;
    user?: User;
    status?: string;
    playerRole?: string;
}

