/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Field } from './field';
import { User } from './user';
import { LocalTime } from './localTime';


export interface Match { 
    matchId?: number;
    field?: Field;
    type?: string;
    pubStatus?: string;
    privStatus?: string;
    matchDate?: string;
    startTime?: LocalTime;
    endTime?: LocalTime;
    minPlayers?: number;
    maxPlayers?: number;
    pricing?: number;
    organiser?: User;
}

