/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MatchPlayerDto } from './matchPlayerDto';
import { MatchDto } from './matchDto';


export interface MatchPlayerDetails { 
    player?: MatchPlayerDto;
    match?: MatchDto;
}

