/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Site } from './site';


export interface SiteClosureDays { 
    closureId?: number;
    siteId?: number;
    closureDate?: string;
    reason?: string;
    forAll?: boolean;
    site?: Site;
}

