/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SiteClosureDays } from './siteClosureDays';
import { LocalTime } from './localTime';


export interface Site { 
    siteId?: number;
    name?: string;
    address?: string;
    openingTime?: LocalTime;
    closingTime?: LocalTime;
    isActive?: boolean;
    closureDays?: Array<SiteClosureDays>;
}

