/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserRoles } from './userRoles';
import { UserPenalties } from './userPenalties';


export interface User { 
    matricule?: string;
    isActive?: boolean;
    firstName?: string;
    lastName?: string;
    email?: string;
    birthDate?: string;
    level?: string;
    lastLogin?: string;
    created?: string;
    auth?: string;
    role?: UserRoles;
    penalties?: Array<UserPenalties>;
}

