/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface UserPenalties { 
    tr?: number;
    user?: User;
    matchId?: number;
    reason?: string;
    startDate?: string;
    endDate?: string;
    isActive?: boolean;
    description?: string;
}

