/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserSiteDto { 
    siteId?: number;
    siteName?: string;
    isPrimary?: boolean;
    isVip?: boolean;
}

