-- SCHEMA A BIT OUT OF DATE SINCE FRONTEND BUILD, BUT GOOD ENOUGH FOR TESTING PURPOSES

CREATE SCHEMA IF NOT EXISTS dbo;
SET SCHEMA dbo;

-- 1. Roles: Defines user roles
CREATE TABLE dbo.Users_Roles (
 id SMALLINT PRIMARY KEY,
 name VARCHAR(20) NOT NULL,
 description VARCHAR(255)
);

-- 2. Users: Stores all user profiles
CREATE TABLE dbo.Users (
    user_id VARCHAR(20) PRIMARY KEY,
    is_active BIT NOT NULL DEFAULT 1,
    fname VARCHAR(50) NOT NULL,
    lname VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    bdate DATE,
    role_id SMALLINT NULL,
    lvl VARCHAR(20) DEFAULT NULL,
    last_login TIMESTAMP,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    auth VARCHAR(255),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES dbo.Users_Roles(id) ON DELETE SET NULL,
    CONSTRAINT check_users_lvl CHECK (lvl IS NULL OR lvl IN ('débutant', 'averti', 'confirmé'))
);

-- 3. Sites: Stores site-specific details
CREATE TABLE dbo.Sites (
    site_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR(255) NOT NULL,
    opening_time TIME NOT NULL,
    closing_time TIME NOT NULL,
    is_active BIT NOT NULL DEFAULT 1
);

-- 4. Site Closure Days: Specific closure dates for each site
CREATE TABLE dbo.Sites_ClosureDays (
    tr INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id INT,
    closure_date DATE NOT NULL,
    reason VARCHAR(255),
    for_all BIT NOT NULL DEFAULT 0,
    CONSTRAINT fk_closure_site FOREIGN KEY (site_id) REFERENCES dbo.Sites(site_id) ON DELETE CASCADE
);

-- 5. Fields : Each site has multiple courts
CREATE TABLE dbo.Fields (
    field_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id INT,
    is_indoor BIT NOT NULL DEFAULT 0,
    is_active BIT NOT NULL DEFAULT 1,
    maintenance_from_date DATE,
    maintenance_to_date DATE,
    CONSTRAINT fk_field_site FOREIGN KEY (site_id) REFERENCES dbo.Sites(site_id) ON DELETE CASCADE
);

-- 6. Sessions
CREATE TABLE dbo.Sites_Sessions (
    session_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id INT NOT NULL,
    match_sessions_json CLOB NOT NULL,
    CONSTRAINT uq_site_session UNIQUE (site_id),
    CONSTRAINT fk_session_site FOREIGN KEY (site_id) REFERENCES dbo.Sites(site_id) ON DELETE CASCADE
);

-- 7. User Accounts Status: Tracks financial status of each user
CREATE TABLE dbo.Users_Accounts (
    tr INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(20) NOT NULL,
    balance DECIMAL(6, 2) DEFAULT 0.00,
    last_upd TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(10) NOT NULL DEFAULT 'clear',
    CONSTRAINT uq_users_accounts_user UNIQUE (user_id),
    CONSTRAINT check_user_status CHECK (status IN ('clear', 'debt')),
    CONSTRAINT fk_users_accounts_user FOREIGN KEY (user_id) REFERENCES dbo.Users(user_id)
);

-- 8. User Sites: Links users to their sites
CREATE TABLE dbo.Users_Sites (
    user_id VARCHAR(20),
    site_id INT,
    is_primary BIT NOT NULL DEFAULT 1,
    is_vip BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, site_id),
    CONSTRAINT fk_users_sites_user FOREIGN KEY (user_id) REFERENCES dbo.Users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_users_sites_site FOREIGN KEY (site_id) REFERENCES dbo.Sites(site_id) ON DELETE CASCADE
);

-- 9. Matches: Private/public matches
CREATE TABLE dbo.Matches (
    match_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field_id INT,
    type VARCHAR(10) NOT NULL,
    pub_status VARCHAR(15),
    priv_status VARCHAR(15),
    match_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    min_players INT DEFAULT 4,
    max_players INT DEFAULT 4,
    pricing INT DEFAULT 60,
    organiser_id VARCHAR(20),
    CONSTRAINT fk_matches_field FOREIGN KEY (field_id) REFERENCES dbo.Fields(field_id) ON DELETE SET NULL,
    CONSTRAINT fk_matches_organiser FOREIGN KEY (organiser_id) REFERENCES dbo.Users(user_id),
    CONSTRAINT check_match_time CHECK (end_time > start_time),
    CONSTRAINT chk_match_type CHECK (type IN ('private', 'public')),
    CONSTRAINT chk_pub_status CHECK (pub_status IN ('closed', 'open', 'completed', 'cancelled') OR pub_status IS NULL),
    CONSTRAINT chk_priv_status CHECK (priv_status IN ('awaiting', 'confirmed', 'completed', 'cancelled') OR priv_status IS NULL),
    CONSTRAINT check_match_status CHECK (
        (type = 'private' AND priv_status IS NOT NULL AND pub_status IS NULL) OR
        (type = 'public' AND pub_status IS NOT NULL AND priv_status IS NULL)
    )
);

-- 10. Match Payments: Logs all match payments and status
CREATE TABLE dbo.Match_Payments (
    tr INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(20),
    match_id INT,
    amount DECIMAL(6, 2) NOT NULL,
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(15) NOT NULL,
    payment_method VARCHAR(10) NOT NULL,
    CONSTRAINT fk_match_payment_user FOREIGN KEY (user_id) REFERENCES dbo.Users(user_id),
    CONSTRAINT fk_match_payment_match FOREIGN KEY (match_id) REFERENCES dbo.Matches(match_id),
    CONSTRAINT chk_payment_status CHECK (status IN ('clear', 'pending', 'cancelled', 'failed', 'refunded')),
    CONSTRAINT chk_pmatch_payment_method CHECK (payment_method IN ('COUNTER', 'CARD'))
);

-- 11. Penalties: Blocks bookings if active
CREATE TABLE dbo.Users_Penalties (
    tr INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(20),
    match_id INT,
    reason VARCHAR(25) NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    is_active BIT NOT NULL DEFAULT 1,
    description VARCHAR(255),
    CONSTRAINT fk_penalty_user FOREIGN KEY (user_id) REFERENCES dbo.Users(user_id),
    CONSTRAINT fk_penalty_match FOREIGN KEY (match_id) REFERENCES dbo.Matches(match_id),
    CONSTRAINT check_penalty_reason CHECK (reason IN ('unpaid_balance', 'no_show', 'insufficient_players')),
    CONSTRAINT check_penalty_date CHECK (end_date > start_date)
);

-- 12. Match Players: Players in each match
CREATE TABLE dbo.Match_Players (
    tr INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id INT NOT NULL,
    user_id VARCHAR(20),
    status VARCHAR(15) NOT NULL,
    p_role VARCHAR(2) NOT NULL,
    CONSTRAINT fk_match_player_match FOREIGN KEY (match_id) REFERENCES dbo.Matches(match_id),
    CONSTRAINT fk_match_player_user FOREIGN KEY (user_id) REFERENCES dbo.Users(user_id),
    CONSTRAINT chk_session_status CHECK (status IN ('approved', 'pending', 'declined', 'invited')),
    CONSTRAINT check_player_role CHECK (p_role IN ('p1', 'p2', 'p3', 'p4')),
    CONSTRAINT uq_match_role UNIQUE (match_id, p_role)
);


-- DOESN'T WORK IN H2, WE CAN SKIP IT FOR TESTING
-- INDEX Create a filtered unique index to enforce uniqueness only when user_id is not NULL
--CREATE UNIQUE INDEX uq_match_user_not_null
--    ON dbo.Match_Players (match_id, user_id)
--    WHERE user_id IS NOT NULL;

