export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './availabilityController.service';
import { AvailabilityControllerService } from './availabilityController.service';
export * from './fieldController.service';
import { FieldControllerService } from './fieldController.service';
export * from './infoController.service';
import { InfoControllerService } from './infoController.service';
export * from './matchController.service';
import { MatchControllerService } from './matchController.service';
export * from './matchCreationController.service';
import { MatchCreationControllerService } from './matchCreationController.service';
export * from './matchPaymentController.service';
import { MatchPaymentControllerService } from './matchPaymentController.service';
export * from './matchPlayerController.service';
import { MatchPlayerControllerService } from './matchPlayerController.service';
export * from './migrateUserController.service';
import { MigrateUserControllerService } from './migrateUserController.service';
export * from './siteController.service';
import { SiteControllerService } from './siteController.service';
export * from './statisticsController.service';
import { StatisticsControllerService } from './statisticsController.service';
export * from './testLoginController.service';
import { TestLoginControllerService } from './testLoginController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './userRegistrationController.service';
import { UserRegistrationControllerService } from './userRegistrationController.service';
export const APIS = [AuthControllerService, AvailabilityControllerService, FieldControllerService, InfoControllerService, MatchControllerService, MatchCreationControllerService, MatchPaymentControllerService, MatchPlayerControllerService, MigrateUserControllerService, SiteControllerService, StatisticsControllerService, TestLoginControllerService, UserControllerService, UserRegistrationControllerService];
