spring.application.name=BE_ProjetDV2026-PMALIOUKOV

# Jasypt configuration
jasypt.encryptor.password=EPHEC2026
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.key-obtention-iterations=1000
jasypt.encryptor.pool-size=1

# Database connection
spring.datasource.url=jdbc:sqlserver://localhost\\SQL_EPS;databaseName=p3sgbd-prodv;encrypt=true;trustServerCertificate=true
spring.datasource.username=PRO
spring.datasource.password=ENC(y6mXmcAGwlM1A8HVKfS/kVbTy87KLeeR)
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.default_schema=dbo

# JWT - Server side key for improved security, should be kept secret and not hardcoded in frontend
security.jwt.secret=GH4vKrzJ+53PfL+px0fgyT/Do07H/a7qmEhEsW4ueMILOU6GGE+HMz/5IVWzkGgBxu7PuvMoV0Nlz8x6Er9fpg==
security.jwt.expiration-seconds=900

#logging.level.org.springframework.security=DEBUG