spring.application.name=BE_ProjetDV2026-PMALIOUKOV

# Database connection
spring.datasource.url=jdbc:sqlserver://localhost\\SQL_EPS;databaseName=p3sgbd-prodv;encrypt=true;trustServerCertificate=true
spring.datasource.username=PRO
spring.datasource.password=
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.default_schema=dbo

# JWT - Server side key for improved security, should be kept secret and not hardcoded in frontend
security.jwt.secret=GH4vKrzJ+53PfL+px0fgyT/Do07H/a7qmEhEsW4ueMILOU6GGE+HMz/5IVWzkGgBxu7PuvMoV0Nlz8x6Er9fpg==
security.jwt.expiration-seconds=900